07 radio
js-tasks-ru/htmlcss-20210708_andrew-rubanov pull request #17
Opened 2021-10-10 05:41 UTC by MaxPower55

2021-10-10 05:41 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-10-10 15:42 UTC, GSemikozov approved these changes

2021-10-10 15:42 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2021-10-11 07:51 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-10-11 18:57 UTC, GSemikozov requested changes

2021-10-11 18:57 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +.checkbox:checked, .checkbox:not(:checked) {
можно просто .checkbox :) + outline: none + clip: rect(0 0 0 0)

2021-10-11 18:57 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +    position: absolute;
тут не обязательно использовать абсолют

2021-10-12 12:44 UTC, MaxPower55 commented on 07-lection5/01-checkbox/checkbox.css
> +.checkbox:checked, .checkbox:not(:checked) {
добавил эти правила в .cb__input

2021-10-12 12:45 UTC, MaxPower55 commented on 07-lection5/01-checkbox/checkbox.css
> +    position: absolute;
убрал позиционирование.

2021-10-23 19:17 UTC, GSemikozov approved these changes

2021-10-23 19:17 UTC, merged