сделал тогглы
js-tasks-ru/htmlcss-20210708_andrew-rubanov pull request #18
Opened 2021-10-12 11:25 UTC by MaxPower55

2021-10-12 11:25 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-10-12 11:33 UTC, GSemikozov requested changes

2021-10-12 11:33 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +.toggle__input:checked, .toggle__input:not(:checked) {
можно просто .toggle__input

2021-10-12 11:33 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +    box-sizing: border-box;
32-33 - ненужное дублирование кода

2021-10-12 11:33 UTC, GSemikozov commented on 07-lection5/03-toggler/index.html
> +                <span class="toggle__arm"></span>
по структуре arm должен быть вложен в case

2021-10-12 12:52 UTC, MaxPower55 commented on 07-lection5/03-toggler/toggler.css
> +.toggle__input:checked, .toggle__input:not(:checked) {
исправил

2021-10-12 12:53 UTC, MaxPower55 commented on 07-lection5/03-toggler/toggler.css
> +    box-sizing: border-box;
Ага, увидел, что дублится. Убрал лишние строки

2021-10-23 11:37 UTC, MaxPower55 commented on 07-lection5/03-toggler/index.html
> +                <span class="toggle__arm"></span>
Вложил переключатель arm в оболочку case. Вроде всё работает.

2021-10-23 19:17 UTC, GSemikozov approved these changes

2021-10-23 19:17 UTC, merged