03 accordion
js-tasks-ru/htmlcss-20210708_andrew-rubanov pull request #5
Opened 2021-07-25 09:39 UTC by MaxPower55

2021-07-25 09:39 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-07-25 19:06 UTC, GSemikozov requested changes

2021-07-25 19:06 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin: 50px;
внешние отступы на ровне блока не задаем, это противоречит БЭМ. Если необходимо двигать блок относительно других блоков - используем миксы

2021-07-25 19:06 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    background: #FFFFFF;
цвета необходимо забирать из переменных

2021-07-25 19:06 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.item_header {
.item_header -> .accordion__header-item {

2021-07-25 19:06 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin-top: 24px;
22-24 строки - чтобы не отталкивать дочерние элементы от границ родительского блока через марджины проще задать внутренние отступы на уровне блока - тогда не нужно будет каждому дочернему элементу назначать марджины

2021-07-28 05:09 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-07-28 05:56 UTC, MaxPower55 commented on 03-lection1/02-accordion/accordion.css
> +.item_header {
Объясни пожалуйста, я не пойму, родительский элемент аккордион, в нём находится блок item, а в нём элемент header. Почему ты поменял местами header и item ?

2021-07-28 07:12 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-28 23:16 UTC, GSemikozov requested changes

2021-07-28 23:16 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion_item_header {
.accordion_item_header -> .accordion__item-header

2021-07-28 23:16 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding: 24px 540px 16px 32px;
какой-то дикий отступ справа, вряд ли так должно быть)
скорее всего было просто скопировано из фигмы. Но - стоит помнить, что длина строки текста может быть разной, так что отступы должны быть универсальными - в данном случае, предполагается что справа будет столько же сколько и слева

2021-07-28 23:16 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.item_content {
.item_content -> .accordion__content

2021-07-28 23:16 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +summary {
30-41 строки - в БЭМ мы не используем селекторы тегов, если нужно сделать общие сбросы - их можно описать в normalize.css, если в контексте компонента - тогда нужно использовать БЭМ-нейминг

2021-07-29 04:26 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-07-29 07:10 UTC, MaxPower55 commented on 03-lection1/02-accordion/accordion.css
> +.accordion_item_header {
Ага, через два нижних подчёркивания название элемента. Исправил.

2021-07-29 07:12 UTC, MaxPower55 commented on 03-lection1/02-accordion/accordion.css
> +    padding: 24px 540px 16px 32px;
Да, я взял из фигмы размер. Честно сказать тоже подумал сделать одинаковый слева и справа по 32рх, но внутреннее сомнение взяло верх и решил полностью скопировать "пиксель пёрфект" из фигмы. Исправил на 32рх.

2021-07-29 07:15 UTC, MaxPower55 commented on 03-lection1/02-accordion/accordion.css
> +.item_content {
Исправил.

2021-07-29 07:17 UTC, MaxPower55 commented on 03-lection1/02-accordion/accordion.css
> +summary {
Переделал на бэм-нейминг.

2021-07-29 07:20 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-29 07:40 UTC, GSemikozov requested changes

2021-07-29 07:40 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__item_header {
.accordion__item_header -> .accordion__item-header
не допушили)

2021-07-29 10:18 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-07-29 10:35 UTC, MaxPower55 commented on 03-lection1/02-accordion/accordion.css
> +.accordion__item_header {
Исправил на "-"

2021-07-29 10:37 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-30 18:21 UTC, GSemikozov approved these changes, later dismissed

2021-07-30 18:21 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2021-08-10 11:39 UTC, GSemikozov approved these changes

2021-08-10 11:39 UTC, merged